name: "ci"
on:
  pull_request_target:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run lint
  run-test:
    runs-on: ubuntu-latest
    env:
      DIRECTCLOUDBOX_SERVICE: ${{ secrets.DIRECTCLOUDBOX_SERVICE }}
      DIRECTCLOUDBOX_SERVICE_KEY: ${{ secrets.DIRECTCLOUDBOX_SERVICE_KEY }}
      DIRECTCLOUDBOX_CODE: ${{ secrets.DIRECTCLOUDBOX_CODE }}
      DIRECTCLOUDBOX_ID: ${{ secrets.DIRECTCLOUDBOX_ID }}
      DIRECTCLOUDBOX_PASSWORD: ${{ secrets.DIRECTCLOUDBOX_PASSWORD }}
      DIRECTCLOUDBOX_NODE: "1"
      DIRECTCLOUDBOX_FILE_PATH: "index.js"
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: node index.js
