name: "lint"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run lint
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: nom ci
      - run: node index.js
        env:
          DIRECTCLOUDBOX_SERVICE: ${{ secrets.DIRECTCLOUDBOX_SERVICE }}
          DIRECTCLOUDBOX_SERVICE_KEY: ${{ secrets.DIRECTCLOUDBOX_SERVICE_KEY }}
          DIRECTCLOUDBOX_CODE: ${{ secrets.CODE }}
          DIRECTCLOUDBOX_ID: ${{ secrets.DIRECTCLOUDBOX_ID }}
          DIRECTCLOUDBOX_PASSWORD: ${{ secrets.DIRECTCLOUDBOX_PASSWORD }}
          DIRECTCLOUDBOX_NDOE: "1"
          DIRECTCLOUDBOX_FILE_PATH: "index.js"
